### PR TITLE
allow snapshots of single tiles

### PR DESCRIPTION
**Pull request by moinmoin-sh**
This PR enables to take snapshots of single tiles of the current sceen.
The api changed to  `http://<your_ip>/api/snapshot.bmp?tile=1` where tile = 1..6. Missing or wrong query results in the standard full screen snapshot.

### CODE REVIEW

**Comment by austinscreations** [comment]
FYI should look at the other open PR, I found the issue regarding ethernet snapshot to work.

**Comment by moinmoin-sh** [comment]
focused on my own stuff first ...

I think I should add the `#if defs` as apropriate to my PR if you agree. (would make your PR obsolete)

**Comment by austinscreations** [comment]
Oh that's fine, was just pointing it out. The only reason it hadn't already been merged is @sumnerboy12 wanted you to look / weight in on it

**Comment by moinmoin-sh** [comment]
I made a different change to solve the ethernet issue with large payloads.

I send the image data row by row (~1k) which is working for ethernet and wifi. The payload per write cycle is well below the 2k buffer limit. This solution makes much more sense to me than the writeP usage which helps for an unknown reason .

**Comment by austinscreations** [comment]
sounds good to me. i assume it's not slowing down responsiveness with the way your doing it? full snapshot for me was taking less than 1.5 seconds i think.

**Comment by moinmoin-sh** [comment]
Debug builds are uploaded to discord. Please do some comparison / testing

**Comment by austinscreations** [comment]
so my original fix:
using writeP on WiFi = `12.64` seconds
using write for WiFi = `1.47` seconds
now writeP is the only one that will work with ethernet but it takes `1.12` seconds

the new proposal:
WiFi `3.01` seconds
Ethernet `1.17s` seconds

**Review by sumnerboy12 — APPROVED** [review]
This looks good to me.

**Comment by sumnerboy12** [comment]
Just to confirm, this supersedes #5?

**Comment by austinscreations** [comment]
> Just to confirm, this supersedes #5?

correct

**Pull request merged**
